name: flutter_beautiful_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  adaptive_components: ^0.0.9
  collection: ^1.17.1
  cupertino_icons: ^1.0.2
  desktop_window: ^0.4.0
  dynamic_color: ^1.6.5
  english_words: ^4.0.0
  flutter_bloc: ^8.1.2
  freezed_annotation: ^2.2.0
  go_router: ^7.0.1
  universal_platform: ^1.0.0+1
  url_launcher: ^6.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/playlists/
    - assets/images/albums/
    - assets/images/artists/
    - assets/images/news/
